# Generated by Django 4.0.4 on 2022-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
