# Generated by Django 4.0.4 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_blog_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
