# Generated by Django 4.0.4 on 2022-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_plan_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
