# Generated by Django 4.0.4 on 2022-04-26 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_plan_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
