# Generated by Django 4.0.4 on 2022-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_plan_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
