# Generated by Django 4.0.4 on 2022-04-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_plan_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='plan_level',
            new_name='plan_type',
        ),
    ]
