# Generated by Django 4.0.4 on 2022-04-17 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=255)),
                ('pg', models.CharField(max_length=255)),
                ('paid_amount', models.IntegerField()),
                ('paid_at', models.DateTimeField(default=datetime.datetime.now)),
                ('merchant_uid', models.CharField(max_length=255, unique=True)),
                ('imp_uid', models.CharField(max_length=255)),
                ('apply_num', models.CharField(max_length=255)),
                ('is_refund', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
