# Generated by Django 4.0.4 on 2022-04-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_refund',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='apply_num',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
