# Generated by Django 4.0.4 on 2022-04-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_is_paid_remove_payment_is_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='apply_num',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
