# Generated by Django 4.0.4 on 2022-04-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_apply_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='referral',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
