# Generated by Django 4.0.4 on 2022-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_apply_num_payment_pg_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='use_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
