# Generated by Django 4.0.4 on 2022-04-17 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gig.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('product_url', models.CharField(blank=True, max_length=255)),
                ('provide', models.CharField(max_length=255)),
                ('guide_line', models.TextField()),
                ('limit_offer', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('reward', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('finished_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(default=datetime.datetime.now)),
                ('merchant_uid', models.CharField(max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_item', models.BooleanField(default=False)),
                ('is_recommend', models.BooleanField(default=False)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to=gig.models.upload_to)),
            ],
            options={
                'db_table': 'gig_campaign',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GigCampaignOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.CharField(max_length=255)),
                ('sns_url', models.CharField(max_length=255)),
                ('offer_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_picked', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gigcampaign')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gig_campaign_offer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GigCampaignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_confirm', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gigcampaignoffer')),
            ],
            options={
                'db_table': 'gig_campaign_review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GigCampaignFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_at', models.DateTimeField(default=datetime.datetime.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gigcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gig_campaign_favorite',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='favorite_user',
            field=models.ManyToManyField(blank=True, related_name='favorite_user_set', through='gig.GigCampaignFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='offer_user',
            field=models.ManyToManyField(blank=True, related_name='offer_user_set', through='gig.GigCampaignOffer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gigcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
