# Generated by Django 4.0.4 on 2022-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='pay_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
