# Generated by Django 4.0.4 on 2022-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_gigcampaign_pay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigcampaign',
            name='use_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
