# Generated by Django 4.0.4 on 2022-04-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_gigcampaign_use_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcampaign',
            name='use_point',
        ),
    ]
