# Generated by Django 4.0.4 on 2022-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('target', models.IntegerField()),
                ('hit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'support_faq',
                'managed': True,
            },
        ),
    ]
