# Generated by Django 4.0.4 on 2022-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrank',
            name='blog_id',
        ),
        migrations.AlterField(
            model_name='blogrank',
            name='blog_link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
